# Generated by Django 4.0.6 on 2022-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glcm', '0002_penerbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah_buku',
            field=models.IntegerField(null=True),
        ),
    ]
