# Generated by Django 4.0.6 on 2022-07-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glcm', '0005_buku_cover_buku_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='waktu',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
